name = "image-uploader"
main = "src/worker.ts"
compatibility_date = "2024-04-14"
workers_dev = false

[vars]
IMAGE_HOST = "image.example.com"

[[routes]]
pattern = "upload.example.com/*"
zone_name = "example.com"

[[routes]]
pattern = "upload.example.com"
zone_name = "example.com"

[[d1_databases]]
binding = "IMAGE_D1"
database_name = "d1-example-com"
database_id = "d1-database-id"
migrations_dir = "./d1_migrations"

[[r2_buckets]]
binding = "IMAGE_R2"
bucket_name = "r2-example-com"
